# fly.toml app configuration file generated for strongbox-fly-test on 2024-12-24T12:07:07-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'strongbox-fly-test'
primary_region = 'lax'

[build]
  image = 'flyio/hellofly:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
